default:
    before:
        - composer.json
        - LICENSE
        - .gitignore
install:
    before:
        - composer/install
update:
    before:
        - composer/update
fix:
    before:
        - php-cs-fixer
test:
    before:
        - install
        - phpunit
build:
    before:
        - fix
        - test
check:
    before:
        - phpstan

.php_cs:
    level: psr2

phpunit:
    colors:         always
    coverageText:   true
    coverageClover: true

vcsignore:
    coverage.clover: dynamic files
    .phpunit.result.cache: dynamic files

