app:
    controllerMap:
        default:
            __class: hidev\console\CommonController
            before:
                - composer.json
                - README.md
                - LICENSE
                - .gitignore
                - .travis.yml
                - .scrutinizer.yml
        install:
            before:
                - composer/install
        update:
            before:
                - composer/update
        fix:
            before:
                - php-cs-fixer
        test:
            before:
                - install
                - phpunit
        build:
            before:
                - fix
                - test
        check:
            before:
                - phpstan

readme:
    badges:
        packagist.stable:
        packagist.downloads:
        travis.build:
        scrutinizer.coverage:
        scrutinizer.quality:

.php_cs:
    level: psr2

phpunit:
    colors:         always
    coverageText:   true
    coverageClover: true

vcsignore:
    coverage.clover: phpunit generated files

.travis.yml:
    sudo: false
    dist: trusty
    language: php
    php:
        - 7.1
        - 7.2
    cache:
        directories:
            - $HOME/.composer/cache
    before_install:
        - composer self-update
        - composer --version

travis:
    after_script:
        - scrutinizer/upload-coverage

.scrutinizer.yml:
    checks:
        php:
            code_rating: true
            duplication: true
    tools:
        php_code_coverage:
            enabled: true
        external_code_coverage:
            timeout: 600
    build:
        nodes:
            analysis:
                tests:
                    override:
                        - php-scrutinizer-run

theme:
    pathMap:
        '@hidev/views':
            - '@hidev/php/views'

